### ISSUE TITLE
wkhtmltopdf download URL moved, fails to install.

### ISSUE THREAD

**Issue by tmertens** [rafaelp/heroku-buildpack-wkhtmltopdf#3]
The wkhtmltopdf binary fails to download/install because the URL is no longer valid.  The buildpack fails to notice and should check the MD5SUM of the binary before attempting to install. But, more importantly, the buildpack needs to be updated with the correct URL: http://downloads.sourceforge.net/project/wkhtmltopdf/archive/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb

**Comment by Yogu** [comment]
See wkhtmltopdf/wkhtmltopdf#2158 for the upstream discussion on the underlying problem.

**Comment by rdetert** [comment]
Getting errors as well when deploying to Heroku:

```
-----> Fetching custom git buildpack... done
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/rafaelp/heroku-buildpack-wkhtmltopdf
=====> Detected Framework: wkhtmltopdf
-----> Installing wkhtmltopdf 0.12.1
dpkg-deb: error: `/app/tmp/cache/wkhtmltopdf.deb' is not a debian format archive
       Writing profile script
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-ruby.git
=====> Detected Framework: Ruby
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.0.0
```

After the deploy:

```
$  heroku run "wkhtmltopdf -V"

/app/vendor/bundle/ruby/2.0.0/gems/bundler-1.7.12/lib/bundler/rubygems_integration.rb:309:in `block in replace_bin_path': undefined method `name' for nil:NilClass (NoMethodError)
    from /app/vendor/bundle/bin/wkhtmltopdf:16:in `<main>'
```

**Comment by dgcastil** [comment]
same here

**Comment by toncid** [comment]
New DEB repo: http://download.gna.org/wkhtmltopdf/0.12/0.12.2.1/

**Comment by toncid** [comment]
I've forked the buildpack and updated the download URL: https://github.com/toncid/heroku-buildpack-wkhtmltopdf

**Comment by ratbeard** [comment]
@toncid 's repo worked for me.  I had to clear my cache on heroku using:

```
heroku plugins:install https://github.com/heroku/heroku-repo.git
heroku repo:purge_cache
```

**Comment by rafaelp** [comment]
This is fixed now, sorry for delay.
